language: php

# keep verisions minimal to limit total
# builds on free service. politeness.
php:
    - "5.6"

services:
    - mysql

addons:
    code_climate:
        repo_token: 31b35fa0187cea3c61746a1235b01bd7bfea3ab1b15c80e4a03448c36c6ec909

# test both msyqli and PDO 
install:
    - mysql -e "create database IF NOT EXISTS test;" -uroot
    - mysql -e "create table mock (id int not null auto_increment, val varchar(20), primary key (id));" -uroot test
    - mysql -e "create view vmock as select id, val from mock;" -uroot test
    - composer require codeclimate/php-test-reporter 

after_script:
    - vendor/bin/test-reporter

