language: php

# keep verisions minimal to limit total
# builds on free service. politeness.
php:
    - "5.6"

addons:
    code_climate:
        repo_token: 3835776b3b5113755de86e454eb6725bac11cf80b19c33172b7213af9da4ac20

# test both msyqli and PDO 
install:
    - composer require codeclimate/php-test-reporter 

after_script:
    - vendor/bin/test-reporter

